# Generated by Django 4.2.5 on 2024-02-25 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_stu_question_stuexam_db_sturesults_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuexam_db',
            name='student',
        ),
        migrations.AddField(
            model_name='stuexam_db',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
