# Generated by Django 4.2.5 on 2024-03-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_stuexam_db_student_stuexam_db_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='stream',
            new_name='Grade',
        ),
    ]
