# Generated by Django 4.2.5 on 2024-03-22 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_rename_stream_studentinfo_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuexam_db',
            name='student',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
