# Generated by Django 4.2.5 on 2024-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_alter_exam_model_end_time_and_more'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyinfo',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='questions.student'),
        ),
    ]
