# Generated by Django 4.2.5 on 2024-03-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyinfo_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyinfo',
            name='students',
        ),
    ]
