# Generated by Django 4.2.5 on 2024-02-25 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_grade_name_grade_grade_grade_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='grade_name',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 16, 13, 12, 643479)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 16, 13, 12, 643479)),
        ),
    ]
