# Generated by Django 4.2.5 on 2024-02-25 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_rename_grade_grade_grade_name_remove_grade_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 17, 13, 4, 486751)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 17, 13, 4, 486751)),
        ),
    ]
