# Generated by Django 4.2.5 on 2024-03-08 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 18, 6, 45, 912632)),
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='professor',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 18, 6, 45, 912632)),
        ),
        migrations.AddField(
            model_name='exam_model',
            name='professor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
