# Generated by Django 4.2.5 on 2024-03-15 10:05

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_exam_model_end_time_alter_exam_model_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 5, 35, 873055)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 5, 35, 873055)),
        ),
    ]
