# Generated by Django 4.2.5 on 2024-03-15 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 28, 33, 954967)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 28, 33, 954967)),
        ),
    ]
